version: '3.8'
services:

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=u_admin
      - POSTGRES_PASSWORD=wonderWALL=0702
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '7777:77'

volumes:
  postgres: